// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhJ6q2PHxOJ4yn2GFs7Dv5Xwc0RtXdZPg',
    appId: '1:178733000509:web:a7ef5b41583d13c7b74754',
    messagingSenderId: '178733000509',
    projectId: 'hospital-management-app-886db',
    authDomain: 'hospital-management-app-886db.firebaseapp.com',
    storageBucket: 'hospital-management-app-886db.firebasestorage.app',
    measurementId: 'G-9WT7JY9EX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuaqPWrfBrNFOK2wtHuwGlk7n16rPKgNo',
    appId: '1:740718701792:android:d6c33f034f1caade96f485',
    messagingSenderId: '740718701792',
    projectId: 'hospital-management-ce14d',
    storageBucket: 'hospital-management-ce14d.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnG-BtSDES4018VL9vOwz-_0ZDSXM1zug',
    appId: '1:740718701792:ios:19886825b9409bde96f485',
    messagingSenderId: '740718701792',
    projectId: 'hospital-management-ce14d',
    storageBucket: 'hospital-management-ce14d.firebasestorage.app',
    iosBundleId: 'com.ekram.hospitalmanagement',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqU6AcTPfIDSe0AWpoXP4oQqUB_6x2MZg',
    appId: '1:178733000509:ios:8732d909ae70c39db74754',
    messagingSenderId: '178733000509',
    projectId: 'hospital-management-app-886db',
    storageBucket: 'hospital-management-app-886db.firebasestorage.app',
    iosBundleId: 'com.example.hospitalManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-mCYSmc8Dy4OgzGXKNqJeGodkdPpwv28',
    appId: '1:740718701792:web:21120ae10bd664a096f485',
    messagingSenderId: '740718701792',
    projectId: 'hospital-management-ce14d',
    authDomain: 'hospital-management-ce14d.firebaseapp.com',
    storageBucket: 'hospital-management-ce14d.firebasestorage.app',
  );
}
